import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import type { ReviewFinding, Tier } from "../types/core";

export interface PrPayload {
  title: string;
  description: string;
  branch: string;
  findings: ReviewFinding[];
}

export interface PrGateResult {
  accepted: boolean;
  reason?: string;
}

export function evaluatePrGate(params: {
  passRate: number;
  verificationStatus: "passed" | "failed" | "unavailable";
  tier: Tier;
  reviewScore: number;
  findings: ReviewFinding[];
  thresholdScore: number;
}): PrGateResult {
  if (params.verificationStatus === "unavailable" && params.tier !== "EXPRESS") {
    return { accepted: false, reason: "verification_unavailable" };
  }
  if (params.passRate < 1) {
    return { accepted: false, reason: "test_pass_rate_below_100" };
  }
  if (params.reviewScore < params.thresholdScore) {
    return { accepted: false, reason: "review_score_below_threshold" };
  }
  if (params.findings.some((f) => f.severity === "CRITICAL" && !f.resolved)) {
    return { accepted: false, reason: "critical_findings_unresolved" };
  }
  return { accepted: true };
}

/**
 * Push the branch and open a PR using `gh pr create`.
 * Falls back to a local mock URL if gh is unavailable or GITHUB_TOKEN is not set.
 */
export async function createPullRequest(payload: PrPayload): Promise<string> {
  const githubToken = process.env.GITHUB_TOKEN;
  const ghAvailable = isCommandAvailable("gh");

  if (githubToken && ghAvailable) {
    return createPrViaGh(payload);
  }

  // No gh or no token — push branch locally and return a placeholder URL.
  console.warn("[pr] GITHUB_TOKEN not set or `gh` CLI unavailable — skipping real PR creation.");
  const mockId = randomUUID();
  return `https://github.com/local/autoforge/pull/${mockId.slice(0, 8)}?branch=${encodeURIComponent(payload.branch)}`;
}

function createPrViaGh(payload: PrPayload): string {
  // Push branch to origin first (orchestrator holds git credentials via env).
  const pushResult = spawnSync("git", ["push", "--set-upstream", "origin", payload.branch], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: process.env
  });

  if (pushResult.status !== 0) {
    throw new Error(`git push failed: ${pushResult.stderr?.trim()}`);
  }

  const body = buildPrBody(payload);

  const result = spawnSync(
    "gh",
    ["pr", "create", "--title", payload.title, "--body", body, "--head", payload.branch],
    {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, GH_TOKEN: process.env.GITHUB_TOKEN }
    }
  );

  if (result.status !== 0) {
    throw new Error(`gh pr create failed: ${result.stderr?.trim()}`);
  }

  return result.stdout.trim();
}

function buildPrBody(payload: PrPayload): string {
  const lines: string[] = [
    `## Summary\n\n${payload.description}`,
    "## Review Findings\n"
  ];

  const critical = payload.findings.filter((f) => f.severity === "CRITICAL");
  const major = payload.findings.filter((f) => f.severity === "MAJOR");
  const minor = payload.findings.filter((f) => f.severity === "MINOR");

  if (critical.length === 0 && major.length === 0 && minor.length === 0) {
    lines.push("No findings.");
  } else {
    for (const f of critical) lines.push(`- **CRITICAL**: ${f.description}`);
    for (const f of major) lines.push(`- **MAJOR**: ${f.description}`);
    for (const f of minor) lines.push(`- MINOR: ${f.description}`);
  }

  lines.push("\n---\n🤖 Generated by Autoforge");
  return lines.join("\n");
}

/**
 * Merge a PR via `gh pr merge`. No-op if gh is unavailable.
 */
export async function mergePullRequest(prUrl: string): Promise<void> {
  if (!isCommandAvailable("gh") || !process.env.GITHUB_TOKEN) return;
  const result = spawnSync("gh", ["pr", "merge", prUrl, "--squash", "--auto", "--delete-branch"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, GH_TOKEN: process.env.GITHUB_TOKEN }
  });
  if (result.status !== 0) {
    console.warn(`[pr] gh pr merge failed: ${result.stderr?.trim()}`);
  }
}

/**
 * Close a PR without merging. No-op if gh is unavailable.
 */
export async function closePullRequest(prUrl: string): Promise<void> {
  if (!isCommandAvailable("gh") || !process.env.GITHUB_TOKEN) return;
  const result = spawnSync("gh", ["pr", "close", prUrl, "--comment", "Rejected by autoforge reviewer."], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, GH_TOKEN: process.env.GITHUB_TOKEN }
  });
  if (result.status !== 0) {
    console.warn(`[pr] gh pr close failed: ${result.stderr?.trim()}`);
  }
}

function isCommandAvailable(cmd: string): boolean {
  const result = spawnSync(process.platform === "win32" ? "where" : "which", [cmd], {
    stdio: "ignore"
  });
  return result.status === 0;
}
